import type { Metadata } from "next";
import { interTight } from "./font";
import "./globals.css";
import PageTransition from "./components/PageTransition";
import path from "path";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={interTight.className}>
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
